/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { AchievementsDock, AchievementsSnapshot, AchievementsStats, RecentUnlock } from '@deepseek-ai/dsh-achievements/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$616368696576656d656e7473 {
    deepState: () => Promise<RemoteResult<{ enabled: boolean; }>>
    dock: () => Promise<RemoteResult<AchievementsDock>>
    list: () => Promise<RemoteResult<AchievementsSnapshot>>
    recent: () => Promise<RemoteResult<{ unlocks: RecentUnlock[]; }>>
    setDeepInsights: (enabled: boolean) => Promise<RemoteResult<{ enabled: boolean; }>>
    stats: () => Promise<RemoteResult<AchievementsStats>>
  }
  interface TypertRemoteMap {
    'achievements/deepState': () => Promise<RemoteResult<{ enabled: boolean; }>>
    'achievements/dock': () => Promise<RemoteResult<AchievementsDock>>
    'achievements/list': () => Promise<RemoteResult<AchievementsSnapshot>>
    'achievements/recent': () => Promise<RemoteResult<{ unlocks: RecentUnlock[]; }>>
    'achievements/setDeepInsights': (enabled: boolean) => Promise<RemoteResult<{ enabled: boolean; }>>
    'achievements/stats': () => Promise<RemoteResult<AchievementsStats>>
  }
  interface TypertRemoteNamespaceMap {
    'achievements': TypertRemoteNamespace$616368696576656d656e7473
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
