/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_achievements_achievements_deepState_result$schema = z.object({
  'enabled': z.boolean(),
})
const _deepseek_ai_dsh_achievements_achievements_dock_result$schema = z.object({
  'unlocked': z.number().readonly(),
  'total': z.number().readonly(),
  'streak': z.number().readonly(),
  'next': z.union([z.literal(null), z.object({
  'name': z.string().readonly(),
  'icon': z.string().readonly(),
  'current': z.number().readonly(),
  'target': z.number().readonly(),
})]).readonly(),
})
const _deepseek_ai_dsh_achievements_achievements_list_result$schema = z.object({
  'total': z.number().readonly(),
  'unlocked': z.number().readonly(),
  'achievements': z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string().readonly(),
  'desc': z.string().readonly(),
  'icon': z.string().readonly(),
  'category': z.union([z.literal("getting-started"), z.literal("toolsmith"), z.literal("filecraft"), z.literal("orchestration"), z.literal("goals"), z.literal("skill"), z.literal("model"), z.literal("behavior"), z.literal("crossover"), z.literal("hidden")]).readonly(),
  'rarity': z.union([z.literal("common"), z.literal("rare"), z.literal("epic"), z.literal("legendary")]).readonly(),
  'hidden': z.boolean().readonly(),
  'deep': z.boolean().readonly(),
  'deepLocked': z.boolean().readonly(),
  'unlocked': z.boolean().readonly(),
  'unlockedAt': z.union([z.literal(null), z.number()]).readonly(),
  'progress': z.object({
  'current': z.number().readonly(),
  'target': z.number().readonly(),
}).readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_achievements_achievements_recent_result$schema = z.object({
  'unlocks': z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string().readonly(),
  'rarity': z.union([z.literal("common"), z.literal("rare"), z.literal("epic"), z.literal("legendary")]).readonly(),
  'icon': z.string().readonly(),
  'at': z.number().readonly(),
})),
})
const _deepseek_ai_dsh_achievements_achievements_setDeepInsights_parameter_0$schema = z.boolean()
const _deepseek_ai_dsh_achievements_achievements_setDeepInsights_result$schema = z.object({
  'enabled': z.boolean(),
})
const _deepseek_ai_dsh_achievements_achievements_stats_result$schema = z.object({
  'tools': z.array(z.object({
  'name': z.string().readonly(),
  'count': z.number().readonly(),
})).readonly(),
  'tokens': z.object({
  'output': z.number().readonly(),
  'cacheRead': z.number().readonly(),
  'uncached': z.number().readonly(),
  'reasoning': z.number().readonly(),
}).readonly(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-achievements',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-achievements#achievements/deepState',
      service: 'achievements',
      namespace: 'achievements',
      method: 'deepState',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-achievements#achievements/deepState:result',
        schema: _deepseek_ai_dsh_achievements_achievements_deepState_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/achievements/src/index.ts","line":304,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-achievements#achievements/dock',
      service: 'achievements',
      namespace: 'achievements',
      method: 'dock',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-achievements/types#AchievementsDock',
        schema: _deepseek_ai_dsh_achievements_achievements_dock_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/achievements/src/index.ts","line":412,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-achievements#achievements/list',
      service: 'achievements',
      namespace: 'achievements',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-achievements/types#AchievementsSnapshot',
        schema: _deepseek_ai_dsh_achievements_achievements_list_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/achievements/src/index.ts","line":396,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-achievements#achievements/recent',
      service: 'achievements',
      namespace: 'achievements',
      method: 'recent',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-achievements#achievements/recent:result',
        schema: _deepseek_ai_dsh_achievements_achievements_recent_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/achievements/src/index.ts","line":406,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-achievements#achievements/setDeepInsights',
      service: 'achievements',
      namespace: 'achievements',
      method: 'setDeepInsights',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'enabled',
          wire: 'enabled',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-achievements#achievements/setDeepInsights:enabled',
            schema: _deepseek_ai_dsh_achievements_achievements_setDeepInsights_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-achievements#achievements/setDeepInsights:result',
        schema: _deepseek_ai_dsh_achievements_achievements_setDeepInsights_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/achievements/src/index.ts","line":310,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-achievements#achievements/stats',
      service: 'achievements',
      namespace: 'achievements',
      method: 'stats',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-achievements/types#AchievementsStats',
        schema: _deepseek_ai_dsh_achievements_achievements_stats_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/achievements/src/index.ts","line":324,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
